name: Test build and deployment
on:
  push:
    branches:
      - 'release-*'
jobs:
  BuildSimulation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check version
        run : |
          sudo apt-get update && sudo apt-get install jq
          echo $(cat version.json | jq -r '.version')
          release_version=${GITHUB_REF#*release-}
          echo $release_version
          if [ "$(cat version.json | jq -r '.version')" != "$release_version" ]
          then
            echo -e "\n\nrelease version mismatches the version written in version.json. Please change version.json and commit your change.\n\n"
            exit 1
          fi
      - name: Build
        run: |

          echo building and packing and app...
  DeploySimulation:
    runs-on: ubuntu-latest
    needs: BuildSimulation
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo deploying into Test env
